In [54]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
x = pd.DataFrame(iris.data, columns=[iris.feature_names])
y = pd.Series(iris.target)

x.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)
0               5.1              3.5               1.4              0.2
1               4.9              3.0               1.4              0.2
2               4.7              3.2               1.3              0.2
3               4.6              3.1               1.5              0.2
4               5.0              3.6               1.4              0.2

In [55]:
y.value_counts()

0    50
1    50
2    50
Name: count, dtype: int64

In [56]:
import keras

y_converted = keras.utils.to_categorical(y)
y_converted

array([[0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
 

In [57]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y_converted, test_size=0.3)

In [58]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [59]:
model = Sequential()
model.add(Dense(10, input_dim=4, kernel_initializer="normal", activation="relu"))
model.add(Dense(3, kernel_initializer="normal", activation="softmax"))

c:\Users\Matheus\Desktop\Matheus\Programming\Python\MachineLearning\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [60]:
optimizer = SGD()
model.compile(loss="categorical_crossentropy", optimizer=optimizer, metrics=["acc"])

In [61]:
model.fit(
    x_train,
    y_train,
    epochs=500,
    batch_size=60,
    validation_data=(x_test, y_test),
    verbose=1,
)

Epoch 1/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - acc: 0.3952 - loss: 1.1004 - val_acc: 0.1556 - val_loss: 1.1176
Epoch 2/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.4119 - loss: 1.0980 - val_acc: 0.1556 - val_loss: 1.1167
Epoch 3/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - acc: 0.4175 - loss: 1.0979 - val_acc: 0.1556 - val_loss: 1.1158
Epoch 4/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - acc: 0.4230 - loss: 1.0960 - val_acc: 0.1556 - val_loss: 1.1149
Epoch 5/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 0.4341 - loss: 1.0940 - val_acc: 0.1556 - val_loss: 1.1138
Epoch 6/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.4175 - loss: 1.0926 - val_acc: 0.1556 - val_loss: 1.1128
Epoch 7/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - acc: 0.3952 - loss: 1.0944 - val_acc: 0.1556 - val_loss: 1.1121
Epoch 8/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - acc: 0.4119 - loss: 1.0942 - val_acc: 0.1556 - val_loss: 1.1113
Epoch 9/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - acc: 0.4063 - loss:

In [62]:
predicts = model.predict(x_test)

import numpy as np

np.set_printoptions(formatter={"float": lambda x: f"{0:0.2f}"})
print(predicts)

1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/stepWARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001F463612520> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[[0.00 0.00 0.00]
 [0.00 0.00 0.00]
 [0.00 0.00 0.00]
 [0.00 0.00 0.00]
 [0.00 0.00 0.00]
 [0.00 0.00 0.00]
 [0.00 0.00 0.00]
 [0.00 0.00 0.00]
 [0.00 0.00 0.00]
 [0.00 0.00 0.00]
 [0.00 0.00 0.00]
 