In [65]:
import tensorflow as tf
import numpy as np

In [66]:
sentence = tf.constant("Hello, world!")
print(sentence)

content = sentence.numpy().decode("utf-8")
print(content)

tf.Tensor(b'Hello, world!', shape=(), dtype=string)
Hello, world!


In [67]:
a = tf.constant(5)
b = tf.constant(3)
c = tf.constant(2)

d = tf.multiply(a, b)
e = tf.add(b, c)
f = tf.subtract(d, e)

print([i.numpy() for i in [d, e, f]])

[15, 5, 10]


In [68]:
a = tf.constant(5)
b = tf.constant([3, 1, 5, 8, 6])
c = tf.constant([[2, 0, 4], [3, 5, 7]])

print(c)

tf.Tensor(
[[2 0 4]
 [3 5 7]], shape=(2, 3), dtype=int32)


In [69]:
x = tf.constant(4)
y = tf.constant(4.0)
z = tf.constant(4, dtype=tf.float16)

print([i.dtype for i in [x, y, z]])

[tf.int32, tf.float32, tf.float16]


In [70]:
A = tf.constant([[1, 2, 3], [4, 5, 6]])
B = tf.constant([[0, 0], [1, 0], [0, 1]])

result = tf.matmul(A, B)
print(result.numpy())

C = tf.constant([1, 1, 1])
C = tf.expand_dims(C, 1)

result = tf.matmul(A, C)
print(result.numpy())

transposed = tf.transpose(A)
print(transposed.numpy())

[[2 3]
 [5 6]]
[[ 6]
 [15]]
[[1 4]
 [2 5]
 [3 6]]


In [71]:
variable = tf.Variable(2)

print(variable)

matrix = tf.random.normal((3, 5), 0, 1)
variable = tf.Variable(matrix)

print(variable)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[-2.089078  ,  0.21295387,  0.31746966,  1.0230421 , -0.16434233],
       [-1.025067  , -0.17224917,  0.44961858, -0.45272925, -0.9374949 ],
       [-1.0648828 , -1.5159427 ,  1.4046143 ,  0.19071166,  0.97803694]],
      dtype=float32)>
