In [1]:
import tensorflow as tf
import numpy as np

In [3]:
a = tf.constant(5)
b = tf.constant(3)
c = tf.constant(2)

d = tf.multiply(a, b)
e = tf.add(b, c)
f = tf.subtract(d, e)

print([i.numpy() for i in [d, e, f]])

[15, 5, 10]


In [4]:
a = tf.constant(5)
b = tf.constant([3, 1, 5, 8, 6])
c = tf.constant([[2, 0, 4], [3, 5, 7]])

print(c)

tf.Tensor(
[[2 0 4]
 [3 5 7]], shape=(2, 3), dtype=int32)


In [5]:
x = tf.constant(4)
y = tf.constant(4.0)
z = tf.constant(4, dtype=tf.float16)

print([i.dtype for i in [x, y, z]])

[tf.int32, tf.float32, tf.float16]


In [6]:
A = tf.constant([[1, 2, 3], [4, 5, 6]])
B = tf.constant([[0, 0], [1, 0], [0, 1]])

result = tf.matmul(A, B)
print(result.numpy())

C = tf.constant([1, 1, 1])
C = tf.expand_dims(C, 1)

result = tf.matmul(A, C)
print(result.numpy())

transposed = tf.transpose(A)
print(transposed.numpy())

[[2 3]
 [5 6]]
[[ 6]
 [15]]
[[1 4]
 [2 5]
 [3 6]]


In [7]:
variable = tf.Variable(2)

print(variable)

matrix = tf.random.normal((3, 5), 0, 1)
variable = tf.Variable(matrix)

print(variable)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>
<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[ 2.45945   ,  0.90606016,  0.04131892,  0.49653205, -0.17642304],
       [-0.7098515 ,  0.3481515 , -2.565142  , -0.26316023,  1.6164172 ],
       [-0.9490843 ,  0.5140464 ,  1.1764826 , -0.04833468, -1.2236223 ]],
      dtype=float32)>
